name: Code Quality

env:
  cacheId: "6" # increment to expire the cache

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Check style
        run: |
          yarn run prettier

      - name: LINTing
        run: |
          yarn run lint
  test:
    runs-on: ubuntu-latest
    name: Testing
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0"
          cache: "yarn"

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Automated testing
        run: |
          yarn run test
